// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: BuffData.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from BuffData.proto</summary>
public static partial class BuffDataReflection {

  #region Descriptor
  /// <summary>File descriptor for BuffData.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static BuffDataReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cg5CdWZmRGF0YS5wcm90byInCgxCdWZmRGF0YUxpc3QSFwoEZGF0YRgBIAMo",
          "CzIJLkJ1ZmZEYXRhIpIBCghCdWZmRGF0YRIPCgdTcGVsbElEGAEgASgFEhAK",
          "CER1cmF0aW9uGAIgASgFEhAKCEhpdGNvdW50GAMgASgFEhMKC1NwZWxsVHlw",
          "ZUlEGAQgASgFEhAKCEJ1ZmZUeXBlGAUgASgFEhMKC0NvdW50ZXJUeXBlGAYg",
          "ASgFEhUKDUNvdW50ZXJOdW1iZXIYByABKAViBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::BuffDataList), global::BuffDataList.Parser, new[]{ "Data" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::BuffData), global::BuffData.Parser, new[]{ "SpellID", "Duration", "Hitcount", "SpellTypeID", "BuffType", "CounterType", "CounterNumber" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class BuffDataList : pb::IMessage<BuffDataList>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<BuffDataList> _parser = new pb::MessageParser<BuffDataList>(() => new BuffDataList());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<BuffDataList> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::BuffDataReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public BuffDataList() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public BuffDataList(BuffDataList other) : this() {
    data_ = other.data_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public BuffDataList Clone() {
    return new BuffDataList(this);
  }

  /// <summary>Field number for the "data" field.</summary>
  public const int DataFieldNumber = 1;
  private static readonly pb::FieldCodec<global::BuffData> _repeated_data_codec
      = pb::FieldCodec.ForMessage(10, global::BuffData.Parser);
  private readonly pbc::RepeatedField<global::BuffData> data_ = new pbc::RepeatedField<global::BuffData>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::BuffData> Data {
    get { return data_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as BuffDataList);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(BuffDataList other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if(!data_.Equals(other.data_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    hash ^= data_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    data_.WriteTo(output, _repeated_data_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    data_.WriteTo(ref output, _repeated_data_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    size += data_.CalculateSize(_repeated_data_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(BuffDataList other) {
    if (other == null) {
      return;
    }
    data_.Add(other.data_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          data_.AddEntriesFrom(input, _repeated_data_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          data_.AddEntriesFrom(ref input, _repeated_data_codec);
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class BuffData : pb::IMessage<BuffData>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<BuffData> _parser = new pb::MessageParser<BuffData>(() => new BuffData());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<BuffData> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::BuffDataReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public BuffData() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public BuffData(BuffData other) : this() {
    spellID_ = other.spellID_;
    duration_ = other.duration_;
    hitcount_ = other.hitcount_;
    spellTypeID_ = other.spellTypeID_;
    buffType_ = other.buffType_;
    counterType_ = other.counterType_;
    counterNumber_ = other.counterNumber_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public BuffData Clone() {
    return new BuffData(this);
  }

  /// <summary>Field number for the "SpellID" field.</summary>
  public const int SpellIDFieldNumber = 1;
  private int spellID_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int SpellID {
    get { return spellID_; }
    set {
      spellID_ = value;
    }
  }

  /// <summary>Field number for the "Duration" field.</summary>
  public const int DurationFieldNumber = 2;
  private int duration_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Duration {
    get { return duration_; }
    set {
      duration_ = value;
    }
  }

  /// <summary>Field number for the "Hitcount" field.</summary>
  public const int HitcountFieldNumber = 3;
  private int hitcount_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Hitcount {
    get { return hitcount_; }
    set {
      hitcount_ = value;
    }
  }

  /// <summary>Field number for the "SpellTypeID" field.</summary>
  public const int SpellTypeIDFieldNumber = 4;
  private int spellTypeID_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int SpellTypeID {
    get { return spellTypeID_; }
    set {
      spellTypeID_ = value;
    }
  }

  /// <summary>Field number for the "BuffType" field.</summary>
  public const int BuffTypeFieldNumber = 5;
  private int buffType_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int BuffType {
    get { return buffType_; }
    set {
      buffType_ = value;
    }
  }

  /// <summary>Field number for the "CounterType" field.</summary>
  public const int CounterTypeFieldNumber = 6;
  private int counterType_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CounterType {
    get { return counterType_; }
    set {
      counterType_ = value;
    }
  }

  /// <summary>Field number for the "CounterNumber" field.</summary>
  public const int CounterNumberFieldNumber = 7;
  private int counterNumber_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CounterNumber {
    get { return counterNumber_; }
    set {
      counterNumber_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as BuffData);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(BuffData other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (SpellID != other.SpellID) return false;
    if (Duration != other.Duration) return false;
    if (Hitcount != other.Hitcount) return false;
    if (SpellTypeID != other.SpellTypeID) return false;
    if (BuffType != other.BuffType) return false;
    if (CounterType != other.CounterType) return false;
    if (CounterNumber != other.CounterNumber) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (SpellID != 0) hash ^= SpellID.GetHashCode();
    if (Duration != 0) hash ^= Duration.GetHashCode();
    if (Hitcount != 0) hash ^= Hitcount.GetHashCode();
    if (SpellTypeID != 0) hash ^= SpellTypeID.GetHashCode();
    if (BuffType != 0) hash ^= BuffType.GetHashCode();
    if (CounterType != 0) hash ^= CounterType.GetHashCode();
    if (CounterNumber != 0) hash ^= CounterNumber.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (SpellID != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(SpellID);
    }
    if (Duration != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Duration);
    }
    if (Hitcount != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(Hitcount);
    }
    if (SpellTypeID != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(SpellTypeID);
    }
    if (BuffType != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(BuffType);
    }
    if (CounterType != 0) {
      output.WriteRawTag(48);
      output.WriteInt32(CounterType);
    }
    if (CounterNumber != 0) {
      output.WriteRawTag(56);
      output.WriteInt32(CounterNumber);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (SpellID != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(SpellID);
    }
    if (Duration != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Duration);
    }
    if (Hitcount != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(Hitcount);
    }
    if (SpellTypeID != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(SpellTypeID);
    }
    if (BuffType != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(BuffType);
    }
    if (CounterType != 0) {
      output.WriteRawTag(48);
      output.WriteInt32(CounterType);
    }
    if (CounterNumber != 0) {
      output.WriteRawTag(56);
      output.WriteInt32(CounterNumber);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (SpellID != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(SpellID);
    }
    if (Duration != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Duration);
    }
    if (Hitcount != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Hitcount);
    }
    if (SpellTypeID != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(SpellTypeID);
    }
    if (BuffType != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(BuffType);
    }
    if (CounterType != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(CounterType);
    }
    if (CounterNumber != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(CounterNumber);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(BuffData other) {
    if (other == null) {
      return;
    }
    if (other.SpellID != 0) {
      SpellID = other.SpellID;
    }
    if (other.Duration != 0) {
      Duration = other.Duration;
    }
    if (other.Hitcount != 0) {
      Hitcount = other.Hitcount;
    }
    if (other.SpellTypeID != 0) {
      SpellTypeID = other.SpellTypeID;
    }
    if (other.BuffType != 0) {
      BuffType = other.BuffType;
    }
    if (other.CounterType != 0) {
      CounterType = other.CounterType;
    }
    if (other.CounterNumber != 0) {
      CounterNumber = other.CounterNumber;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          SpellID = input.ReadInt32();
          break;
        }
        case 16: {
          Duration = input.ReadInt32();
          break;
        }
        case 24: {
          Hitcount = input.ReadInt32();
          break;
        }
        case 32: {
          SpellTypeID = input.ReadInt32();
          break;
        }
        case 40: {
          BuffType = input.ReadInt32();
          break;
        }
        case 48: {
          CounterType = input.ReadInt32();
          break;
        }
        case 56: {
          CounterNumber = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          SpellID = input.ReadInt32();
          break;
        }
        case 16: {
          Duration = input.ReadInt32();
          break;
        }
        case 24: {
          Hitcount = input.ReadInt32();
          break;
        }
        case 32: {
          SpellTypeID = input.ReadInt32();
          break;
        }
        case 40: {
          BuffType = input.ReadInt32();
          break;
        }
        case 48: {
          CounterType = input.ReadInt32();
          break;
        }
        case 56: {
          CounterNumber = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
