// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: InventoryData.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from InventoryData.proto</summary>
public static partial class InventoryDataReflection {

  #region Descriptor
  /// <summary>File descriptor for InventoryData.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static InventoryDataReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChNJbnZlbnRvcnlEYXRhLnByb3RvIjIKEUludmVudG9yeURhdGFMaXN0Eh0K",
          "BWl0ZW1zGAEgAygLMg4uSW52ZW50b3J5SXRlbSLbAQoNSW52ZW50b3J5SXRl",
          "bRIMCgRuYW1lGAEgASgJEg8KB2l0ZW1faWQYAiABKAUSDAoEaWNvbhgDIAEo",
          "BRIQCghxdWFudGl0eRgEIAEoBRIQCghsb2NhdGlvbhgFIAEoCRIRCglzbG90",
          "X25hbWUYBiABKAkSDwoHc2xvdF9pZBgHIAEoBRIQCghzbG90X2lkMhgIIAEo",
          "BRIRCglpdGVtX2xpbmsYCSABKAkSDwoHbm9fZHJvcBgKIAEoCBIfCgRhdWdz",
          "GAsgAygLMhEuSW52ZW50b3J5QXVnbWVudCJBChBJbnZlbnRvcnlBdWdtZW50",
          "EgwKBHNsb3QYASABKAUSDAoEbmFtZRgCIAEoCRIRCglpdGVtX2xpbmsYAyAB",
          "KAliBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::InventoryDataList), global::InventoryDataList.Parser, new[]{ "Items" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::InventoryItem), global::InventoryItem.Parser, new[]{ "Name", "ItemId", "Icon", "Quantity", "Location", "SlotName", "SlotId", "SlotId2", "ItemLink", "NoDrop", "Augs" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::InventoryAugment), global::InventoryAugment.Parser, new[]{ "Slot", "Name", "ItemLink" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class InventoryDataList : pb::IMessage<InventoryDataList>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<InventoryDataList> _parser = new pb::MessageParser<InventoryDataList>(() => new InventoryDataList());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<InventoryDataList> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::InventoryDataReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public InventoryDataList() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public InventoryDataList(InventoryDataList other) : this() {
    items_ = other.items_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public InventoryDataList Clone() {
    return new InventoryDataList(this);
  }

  /// <summary>Field number for the "items" field.</summary>
  public const int ItemsFieldNumber = 1;
  private static readonly pb::FieldCodec<global::InventoryItem> _repeated_items_codec
      = pb::FieldCodec.ForMessage(10, global::InventoryItem.Parser);
  private readonly pbc::RepeatedField<global::InventoryItem> items_ = new pbc::RepeatedField<global::InventoryItem>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::InventoryItem> Items {
    get { return items_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as InventoryDataList);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(InventoryDataList other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if(!items_.Equals(other.items_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    hash ^= items_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    items_.WriteTo(output, _repeated_items_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    items_.WriteTo(ref output, _repeated_items_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    size += items_.CalculateSize(_repeated_items_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(InventoryDataList other) {
    if (other == null) {
      return;
    }
    items_.Add(other.items_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          items_.AddEntriesFrom(input, _repeated_items_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          items_.AddEntriesFrom(ref input, _repeated_items_codec);
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class InventoryItem : pb::IMessage<InventoryItem>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<InventoryItem> _parser = new pb::MessageParser<InventoryItem>(() => new InventoryItem());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<InventoryItem> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::InventoryDataReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public InventoryItem() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public InventoryItem(InventoryItem other) : this() {
    name_ = other.name_;
    itemId_ = other.itemId_;
    icon_ = other.icon_;
    quantity_ = other.quantity_;
    location_ = other.location_;
    slotName_ = other.slotName_;
    slotId_ = other.slotId_;
    slotId2_ = other.slotId2_;
    itemLink_ = other.itemLink_;
    noDrop_ = other.noDrop_;
    augs_ = other.augs_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public InventoryItem Clone() {
    return new InventoryItem(this);
  }

  /// <summary>Field number for the "name" field.</summary>
  public const int NameFieldNumber = 1;
  private string name_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Name {
    get { return name_; }
    set {
      name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "item_id" field.</summary>
  public const int ItemIdFieldNumber = 2;
  private int itemId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int ItemId {
    get { return itemId_; }
    set {
      itemId_ = value;
    }
  }

  /// <summary>Field number for the "icon" field.</summary>
  public const int IconFieldNumber = 3;
  private int icon_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Icon {
    get { return icon_; }
    set {
      icon_ = value;
    }
  }

  /// <summary>Field number for the "quantity" field.</summary>
  public const int QuantityFieldNumber = 4;
  private int quantity_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Quantity {
    get { return quantity_; }
    set {
      quantity_ = value;
    }
  }

  /// <summary>Field number for the "location" field.</summary>
  public const int LocationFieldNumber = 5;
  private string location_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Location {
    get { return location_; }
    set {
      location_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "slot_name" field.</summary>
  public const int SlotNameFieldNumber = 6;
  private string slotName_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string SlotName {
    get { return slotName_; }
    set {
      slotName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "slot_id" field.</summary>
  public const int SlotIdFieldNumber = 7;
  private int slotId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int SlotId {
    get { return slotId_; }
    set {
      slotId_ = value;
    }
  }

  /// <summary>Field number for the "slot_id2" field.</summary>
  public const int SlotId2FieldNumber = 8;
  private int slotId2_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int SlotId2 {
    get { return slotId2_; }
    set {
      slotId2_ = value;
    }
  }

  /// <summary>Field number for the "item_link" field.</summary>
  public const int ItemLinkFieldNumber = 9;
  private string itemLink_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string ItemLink {
    get { return itemLink_; }
    set {
      itemLink_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "no_drop" field.</summary>
  public const int NoDropFieldNumber = 10;
  private bool noDrop_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool NoDrop {
    get { return noDrop_; }
    set {
      noDrop_ = value;
    }
  }

  /// <summary>Field number for the "augs" field.</summary>
  public const int AugsFieldNumber = 11;
  private static readonly pb::FieldCodec<global::InventoryAugment> _repeated_augs_codec
      = pb::FieldCodec.ForMessage(90, global::InventoryAugment.Parser);
  private readonly pbc::RepeatedField<global::InventoryAugment> augs_ = new pbc::RepeatedField<global::InventoryAugment>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::InventoryAugment> Augs {
    get { return augs_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as InventoryItem);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(InventoryItem other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Name != other.Name) return false;
    if (ItemId != other.ItemId) return false;
    if (Icon != other.Icon) return false;
    if (Quantity != other.Quantity) return false;
    if (Location != other.Location) return false;
    if (SlotName != other.SlotName) return false;
    if (SlotId != other.SlotId) return false;
    if (SlotId2 != other.SlotId2) return false;
    if (ItemLink != other.ItemLink) return false;
    if (NoDrop != other.NoDrop) return false;
    if(!augs_.Equals(other.augs_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Name.Length != 0) hash ^= Name.GetHashCode();
    if (ItemId != 0) hash ^= ItemId.GetHashCode();
    if (Icon != 0) hash ^= Icon.GetHashCode();
    if (Quantity != 0) hash ^= Quantity.GetHashCode();
    if (Location.Length != 0) hash ^= Location.GetHashCode();
    if (SlotName.Length != 0) hash ^= SlotName.GetHashCode();
    if (SlotId != 0) hash ^= SlotId.GetHashCode();
    if (SlotId2 != 0) hash ^= SlotId2.GetHashCode();
    if (ItemLink.Length != 0) hash ^= ItemLink.GetHashCode();
    if (NoDrop != false) hash ^= NoDrop.GetHashCode();
    hash ^= augs_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Name.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Name);
    }
    if (ItemId != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(ItemId);
    }
    if (Icon != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(Icon);
    }
    if (Quantity != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(Quantity);
    }
    if (Location.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(Location);
    }
    if (SlotName.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(SlotName);
    }
    if (SlotId != 0) {
      output.WriteRawTag(56);
      output.WriteInt32(SlotId);
    }
    if (SlotId2 != 0) {
      output.WriteRawTag(64);
      output.WriteInt32(SlotId2);
    }
    if (ItemLink.Length != 0) {
      output.WriteRawTag(74);
      output.WriteString(ItemLink);
    }
    if (NoDrop != false) {
      output.WriteRawTag(80);
      output.WriteBool(NoDrop);
    }
    augs_.WriteTo(output, _repeated_augs_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Name.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Name);
    }
    if (ItemId != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(ItemId);
    }
    if (Icon != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(Icon);
    }
    if (Quantity != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(Quantity);
    }
    if (Location.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(Location);
    }
    if (SlotName.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(SlotName);
    }
    if (SlotId != 0) {
      output.WriteRawTag(56);
      output.WriteInt32(SlotId);
    }
    if (SlotId2 != 0) {
      output.WriteRawTag(64);
      output.WriteInt32(SlotId2);
    }
    if (ItemLink.Length != 0) {
      output.WriteRawTag(74);
      output.WriteString(ItemLink);
    }
    if (NoDrop != false) {
      output.WriteRawTag(80);
      output.WriteBool(NoDrop);
    }
    augs_.WriteTo(ref output, _repeated_augs_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Name.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
    }
    if (ItemId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(ItemId);
    }
    if (Icon != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Icon);
    }
    if (Quantity != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Quantity);
    }
    if (Location.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Location);
    }
    if (SlotName.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(SlotName);
    }
    if (SlotId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(SlotId);
    }
    if (SlotId2 != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(SlotId2);
    }
    if (ItemLink.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(ItemLink);
    }
    if (NoDrop != false) {
      size += 1 + 1;
    }
    size += augs_.CalculateSize(_repeated_augs_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(InventoryItem other) {
    if (other == null) {
      return;
    }
    if (other.Name.Length != 0) {
      Name = other.Name;
    }
    if (other.ItemId != 0) {
      ItemId = other.ItemId;
    }
    if (other.Icon != 0) {
      Icon = other.Icon;
    }
    if (other.Quantity != 0) {
      Quantity = other.Quantity;
    }
    if (other.Location.Length != 0) {
      Location = other.Location;
    }
    if (other.SlotName.Length != 0) {
      SlotName = other.SlotName;
    }
    if (other.SlotId != 0) {
      SlotId = other.SlotId;
    }
    if (other.SlotId2 != 0) {
      SlotId2 = other.SlotId2;
    }
    if (other.ItemLink.Length != 0) {
      ItemLink = other.ItemLink;
    }
    if (other.NoDrop != false) {
      NoDrop = other.NoDrop;
    }
    augs_.Add(other.augs_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Name = input.ReadString();
          break;
        }
        case 16: {
          ItemId = input.ReadInt32();
          break;
        }
        case 24: {
          Icon = input.ReadInt32();
          break;
        }
        case 32: {
          Quantity = input.ReadInt32();
          break;
        }
        case 42: {
          Location = input.ReadString();
          break;
        }
        case 50: {
          SlotName = input.ReadString();
          break;
        }
        case 56: {
          SlotId = input.ReadInt32();
          break;
        }
        case 64: {
          SlotId2 = input.ReadInt32();
          break;
        }
        case 74: {
          ItemLink = input.ReadString();
          break;
        }
        case 80: {
          NoDrop = input.ReadBool();
          break;
        }
        case 90: {
          augs_.AddEntriesFrom(input, _repeated_augs_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          Name = input.ReadString();
          break;
        }
        case 16: {
          ItemId = input.ReadInt32();
          break;
        }
        case 24: {
          Icon = input.ReadInt32();
          break;
        }
        case 32: {
          Quantity = input.ReadInt32();
          break;
        }
        case 42: {
          Location = input.ReadString();
          break;
        }
        case 50: {
          SlotName = input.ReadString();
          break;
        }
        case 56: {
          SlotId = input.ReadInt32();
          break;
        }
        case 64: {
          SlotId2 = input.ReadInt32();
          break;
        }
        case 74: {
          ItemLink = input.ReadString();
          break;
        }
        case 80: {
          NoDrop = input.ReadBool();
          break;
        }
        case 90: {
          augs_.AddEntriesFrom(ref input, _repeated_augs_codec);
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class InventoryAugment : pb::IMessage<InventoryAugment>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<InventoryAugment> _parser = new pb::MessageParser<InventoryAugment>(() => new InventoryAugment());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<InventoryAugment> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::InventoryDataReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public InventoryAugment() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public InventoryAugment(InventoryAugment other) : this() {
    slot_ = other.slot_;
    name_ = other.name_;
    itemLink_ = other.itemLink_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public InventoryAugment Clone() {
    return new InventoryAugment(this);
  }

  /// <summary>Field number for the "slot" field.</summary>
  public const int SlotFieldNumber = 1;
  private int slot_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Slot {
    get { return slot_; }
    set {
      slot_ = value;
    }
  }

  /// <summary>Field number for the "name" field.</summary>
  public const int NameFieldNumber = 2;
  private string name_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Name {
    get { return name_; }
    set {
      name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "item_link" field.</summary>
  public const int ItemLinkFieldNumber = 3;
  private string itemLink_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string ItemLink {
    get { return itemLink_; }
    set {
      itemLink_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as InventoryAugment);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(InventoryAugment other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Slot != other.Slot) return false;
    if (Name != other.Name) return false;
    if (ItemLink != other.ItemLink) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Slot != 0) hash ^= Slot.GetHashCode();
    if (Name.Length != 0) hash ^= Name.GetHashCode();
    if (ItemLink.Length != 0) hash ^= ItemLink.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Slot != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Slot);
    }
    if (Name.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Name);
    }
    if (ItemLink.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(ItemLink);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Slot != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Slot);
    }
    if (Name.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Name);
    }
    if (ItemLink.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(ItemLink);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Slot != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Slot);
    }
    if (Name.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
    }
    if (ItemLink.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(ItemLink);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(InventoryAugment other) {
    if (other == null) {
      return;
    }
    if (other.Slot != 0) {
      Slot = other.Slot;
    }
    if (other.Name.Length != 0) {
      Name = other.Name;
    }
    if (other.ItemLink.Length != 0) {
      ItemLink = other.ItemLink;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Slot = input.ReadInt32();
          break;
        }
        case 18: {
          Name = input.ReadString();
          break;
        }
        case 26: {
          ItemLink = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Slot = input.ReadInt32();
          break;
        }
        case 18: {
          Name = input.ReadString();
          break;
        }
        case 26: {
          ItemLink = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
