// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: TaskData.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from TaskData.proto</summary>
public static partial class TaskDataReflection {

  #region Descriptor
  /// <summary>File descriptor for TaskData.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static TaskDataReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cg5UYXNrRGF0YS5wcm90byInCgxUYXNrRGF0YUxpc3QSFwoEZGF0YRgBIAMo",
          "CzIJLlRhc2tEYXRhItIBCghUYXNrRGF0YRIMCgRzbG90GAEgASgFEg0KBXRp",
          "dGxlGAIgASgJEhMKC2FjdGl2ZV9zdGVwGAMgASgJEhwKFGNvbXBsZXRlZF9v",
          "YmplY3RpdmVzGAQgASgFEhgKEHRvdGFsX29iamVjdGl2ZXMYBSABKAUSDAoE",
          "dHlwZRgGIAEoCRITCgtpc19jb21wbGV0ZRgHIAEoCBIVCg10aW1lcl9kaXNw",
          "bGF5GAggASgJEiIKCm9iamVjdGl2ZXMYCSADKAsyDi5UYXNrT2JqZWN0aXZl",
          "ImMKDVRhc2tPYmplY3RpdmUSDQoFaW5kZXgYASABKAUSEwoLaW5zdHJ1Y3Rp",
          "b24YAiABKAkSDgoGc3RhdHVzGAMgASgJEgwKBHpvbmUYBCABKAkSEAoIb3B0",
          "aW9uYWwYBSABKAhiBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::TaskDataList), global::TaskDataList.Parser, new[]{ "Data" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::TaskData), global::TaskData.Parser, new[]{ "Slot", "Title", "ActiveStep", "CompletedObjectives", "TotalObjectives", "Type", "IsComplete", "TimerDisplay", "Objectives" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::TaskObjective), global::TaskObjective.Parser, new[]{ "Index", "Instruction", "Status", "Zone", "Optional" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class TaskDataList : pb::IMessage<TaskDataList>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<TaskDataList> _parser = new pb::MessageParser<TaskDataList>(() => new TaskDataList());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<TaskDataList> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::TaskDataReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public TaskDataList() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public TaskDataList(TaskDataList other) : this() {
    data_ = other.data_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public TaskDataList Clone() {
    return new TaskDataList(this);
  }

  /// <summary>Field number for the "data" field.</summary>
  public const int DataFieldNumber = 1;
  private static readonly pb::FieldCodec<global::TaskData> _repeated_data_codec
      = pb::FieldCodec.ForMessage(10, global::TaskData.Parser);
  private readonly pbc::RepeatedField<global::TaskData> data_ = new pbc::RepeatedField<global::TaskData>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::TaskData> Data {
    get { return data_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as TaskDataList);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(TaskDataList other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if(!data_.Equals(other.data_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    hash ^= data_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    data_.WriteTo(output, _repeated_data_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    data_.WriteTo(ref output, _repeated_data_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    size += data_.CalculateSize(_repeated_data_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(TaskDataList other) {
    if (other == null) {
      return;
    }
    data_.Add(other.data_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          data_.AddEntriesFrom(input, _repeated_data_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          data_.AddEntriesFrom(ref input, _repeated_data_codec);
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class TaskData : pb::IMessage<TaskData>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<TaskData> _parser = new pb::MessageParser<TaskData>(() => new TaskData());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<TaskData> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::TaskDataReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public TaskData() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public TaskData(TaskData other) : this() {
    slot_ = other.slot_;
    title_ = other.title_;
    activeStep_ = other.activeStep_;
    completedObjectives_ = other.completedObjectives_;
    totalObjectives_ = other.totalObjectives_;
    type_ = other.type_;
    isComplete_ = other.isComplete_;
    timerDisplay_ = other.timerDisplay_;
    objectives_ = other.objectives_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public TaskData Clone() {
    return new TaskData(this);
  }

  /// <summary>Field number for the "slot" field.</summary>
  public const int SlotFieldNumber = 1;
  private int slot_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Slot {
    get { return slot_; }
    set {
      slot_ = value;
    }
  }

  /// <summary>Field number for the "title" field.</summary>
  public const int TitleFieldNumber = 2;
  private string title_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Title {
    get { return title_; }
    set {
      title_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "active_step" field.</summary>
  public const int ActiveStepFieldNumber = 3;
  private string activeStep_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string ActiveStep {
    get { return activeStep_; }
    set {
      activeStep_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "completed_objectives" field.</summary>
  public const int CompletedObjectivesFieldNumber = 4;
  private int completedObjectives_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CompletedObjectives {
    get { return completedObjectives_; }
    set {
      completedObjectives_ = value;
    }
  }

  /// <summary>Field number for the "total_objectives" field.</summary>
  public const int TotalObjectivesFieldNumber = 5;
  private int totalObjectives_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int TotalObjectives {
    get { return totalObjectives_; }
    set {
      totalObjectives_ = value;
    }
  }

  /// <summary>Field number for the "type" field.</summary>
  public const int TypeFieldNumber = 6;
  private string type_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Type {
    get { return type_; }
    set {
      type_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "is_complete" field.</summary>
  public const int IsCompleteFieldNumber = 7;
  private bool isComplete_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool IsComplete {
    get { return isComplete_; }
    set {
      isComplete_ = value;
    }
  }

  /// <summary>Field number for the "timer_display" field.</summary>
  public const int TimerDisplayFieldNumber = 8;
  private string timerDisplay_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string TimerDisplay {
    get { return timerDisplay_; }
    set {
      timerDisplay_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "objectives" field.</summary>
  public const int ObjectivesFieldNumber = 9;
  private static readonly pb::FieldCodec<global::TaskObjective> _repeated_objectives_codec
      = pb::FieldCodec.ForMessage(74, global::TaskObjective.Parser);
  private readonly pbc::RepeatedField<global::TaskObjective> objectives_ = new pbc::RepeatedField<global::TaskObjective>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::TaskObjective> Objectives {
    get { return objectives_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as TaskData);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(TaskData other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Slot != other.Slot) return false;
    if (Title != other.Title) return false;
    if (ActiveStep != other.ActiveStep) return false;
    if (CompletedObjectives != other.CompletedObjectives) return false;
    if (TotalObjectives != other.TotalObjectives) return false;
    if (Type != other.Type) return false;
    if (IsComplete != other.IsComplete) return false;
    if (TimerDisplay != other.TimerDisplay) return false;
    if(!objectives_.Equals(other.objectives_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Slot != 0) hash ^= Slot.GetHashCode();
    if (Title.Length != 0) hash ^= Title.GetHashCode();
    if (ActiveStep.Length != 0) hash ^= ActiveStep.GetHashCode();
    if (CompletedObjectives != 0) hash ^= CompletedObjectives.GetHashCode();
    if (TotalObjectives != 0) hash ^= TotalObjectives.GetHashCode();
    if (Type.Length != 0) hash ^= Type.GetHashCode();
    if (IsComplete != false) hash ^= IsComplete.GetHashCode();
    if (TimerDisplay.Length != 0) hash ^= TimerDisplay.GetHashCode();
    hash ^= objectives_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Slot != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Slot);
    }
    if (Title.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Title);
    }
    if (ActiveStep.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(ActiveStep);
    }
    if (CompletedObjectives != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(CompletedObjectives);
    }
    if (TotalObjectives != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(TotalObjectives);
    }
    if (Type.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(Type);
    }
    if (IsComplete != false) {
      output.WriteRawTag(56);
      output.WriteBool(IsComplete);
    }
    if (TimerDisplay.Length != 0) {
      output.WriteRawTag(66);
      output.WriteString(TimerDisplay);
    }
    objectives_.WriteTo(output, _repeated_objectives_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Slot != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Slot);
    }
    if (Title.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Title);
    }
    if (ActiveStep.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(ActiveStep);
    }
    if (CompletedObjectives != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(CompletedObjectives);
    }
    if (TotalObjectives != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(TotalObjectives);
    }
    if (Type.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(Type);
    }
    if (IsComplete != false) {
      output.WriteRawTag(56);
      output.WriteBool(IsComplete);
    }
    if (TimerDisplay.Length != 0) {
      output.WriteRawTag(66);
      output.WriteString(TimerDisplay);
    }
    objectives_.WriteTo(ref output, _repeated_objectives_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Slot != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Slot);
    }
    if (Title.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Title);
    }
    if (ActiveStep.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(ActiveStep);
    }
    if (CompletedObjectives != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(CompletedObjectives);
    }
    if (TotalObjectives != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(TotalObjectives);
    }
    if (Type.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Type);
    }
    if (IsComplete != false) {
      size += 1 + 1;
    }
    if (TimerDisplay.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(TimerDisplay);
    }
    size += objectives_.CalculateSize(_repeated_objectives_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(TaskData other) {
    if (other == null) {
      return;
    }
    if (other.Slot != 0) {
      Slot = other.Slot;
    }
    if (other.Title.Length != 0) {
      Title = other.Title;
    }
    if (other.ActiveStep.Length != 0) {
      ActiveStep = other.ActiveStep;
    }
    if (other.CompletedObjectives != 0) {
      CompletedObjectives = other.CompletedObjectives;
    }
    if (other.TotalObjectives != 0) {
      TotalObjectives = other.TotalObjectives;
    }
    if (other.Type.Length != 0) {
      Type = other.Type;
    }
    if (other.IsComplete != false) {
      IsComplete = other.IsComplete;
    }
    if (other.TimerDisplay.Length != 0) {
      TimerDisplay = other.TimerDisplay;
    }
    objectives_.Add(other.objectives_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Slot = input.ReadInt32();
          break;
        }
        case 18: {
          Title = input.ReadString();
          break;
        }
        case 26: {
          ActiveStep = input.ReadString();
          break;
        }
        case 32: {
          CompletedObjectives = input.ReadInt32();
          break;
        }
        case 40: {
          TotalObjectives = input.ReadInt32();
          break;
        }
        case 50: {
          Type = input.ReadString();
          break;
        }
        case 56: {
          IsComplete = input.ReadBool();
          break;
        }
        case 66: {
          TimerDisplay = input.ReadString();
          break;
        }
        case 74: {
          objectives_.AddEntriesFrom(input, _repeated_objectives_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Slot = input.ReadInt32();
          break;
        }
        case 18: {
          Title = input.ReadString();
          break;
        }
        case 26: {
          ActiveStep = input.ReadString();
          break;
        }
        case 32: {
          CompletedObjectives = input.ReadInt32();
          break;
        }
        case 40: {
          TotalObjectives = input.ReadInt32();
          break;
        }
        case 50: {
          Type = input.ReadString();
          break;
        }
        case 56: {
          IsComplete = input.ReadBool();
          break;
        }
        case 66: {
          TimerDisplay = input.ReadString();
          break;
        }
        case 74: {
          objectives_.AddEntriesFrom(ref input, _repeated_objectives_codec);
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class TaskObjective : pb::IMessage<TaskObjective>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<TaskObjective> _parser = new pb::MessageParser<TaskObjective>(() => new TaskObjective());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<TaskObjective> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::TaskDataReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public TaskObjective() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public TaskObjective(TaskObjective other) : this() {
    index_ = other.index_;
    instruction_ = other.instruction_;
    status_ = other.status_;
    zone_ = other.zone_;
    optional_ = other.optional_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public TaskObjective Clone() {
    return new TaskObjective(this);
  }

  /// <summary>Field number for the "index" field.</summary>
  public const int IndexFieldNumber = 1;
  private int index_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Index {
    get { return index_; }
    set {
      index_ = value;
    }
  }

  /// <summary>Field number for the "instruction" field.</summary>
  public const int InstructionFieldNumber = 2;
  private string instruction_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Instruction {
    get { return instruction_; }
    set {
      instruction_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "status" field.</summary>
  public const int StatusFieldNumber = 3;
  private string status_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Status {
    get { return status_; }
    set {
      status_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "zone" field.</summary>
  public const int ZoneFieldNumber = 4;
  private string zone_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Zone {
    get { return zone_; }
    set {
      zone_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "optional" field.</summary>
  public const int OptionalFieldNumber = 5;
  private bool optional_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Optional {
    get { return optional_; }
    set {
      optional_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as TaskObjective);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(TaskObjective other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Index != other.Index) return false;
    if (Instruction != other.Instruction) return false;
    if (Status != other.Status) return false;
    if (Zone != other.Zone) return false;
    if (Optional != other.Optional) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Index != 0) hash ^= Index.GetHashCode();
    if (Instruction.Length != 0) hash ^= Instruction.GetHashCode();
    if (Status.Length != 0) hash ^= Status.GetHashCode();
    if (Zone.Length != 0) hash ^= Zone.GetHashCode();
    if (Optional != false) hash ^= Optional.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Index != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Index);
    }
    if (Instruction.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Instruction);
    }
    if (Status.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(Status);
    }
    if (Zone.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(Zone);
    }
    if (Optional != false) {
      output.WriteRawTag(40);
      output.WriteBool(Optional);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Index != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Index);
    }
    if (Instruction.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Instruction);
    }
    if (Status.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(Status);
    }
    if (Zone.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(Zone);
    }
    if (Optional != false) {
      output.WriteRawTag(40);
      output.WriteBool(Optional);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Index != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Index);
    }
    if (Instruction.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Instruction);
    }
    if (Status.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Status);
    }
    if (Zone.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Zone);
    }
    if (Optional != false) {
      size += 1 + 1;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(TaskObjective other) {
    if (other == null) {
      return;
    }
    if (other.Index != 0) {
      Index = other.Index;
    }
    if (other.Instruction.Length != 0) {
      Instruction = other.Instruction;
    }
    if (other.Status.Length != 0) {
      Status = other.Status;
    }
    if (other.Zone.Length != 0) {
      Zone = other.Zone;
    }
    if (other.Optional != false) {
      Optional = other.Optional;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Index = input.ReadInt32();
          break;
        }
        case 18: {
          Instruction = input.ReadString();
          break;
        }
        case 26: {
          Status = input.ReadString();
          break;
        }
        case 34: {
          Zone = input.ReadString();
          break;
        }
        case 40: {
          Optional = input.ReadBool();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Index = input.ReadInt32();
          break;
        }
        case 18: {
          Instruction = input.ReadString();
          break;
        }
        case 26: {
          Status = input.ReadString();
          break;
        }
        case 34: {
          Zone = input.ReadString();
          break;
        }
        case 40: {
          Optional = input.ReadBool();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
